---
    - name: fetch all public ssh keys
      shell: cat ~/.ssh/id_rsa.pub
      delegate_to: localhost
      register: ssh_keys
      tags:
        - ssh

    - name: check keys
      debug: msg="{{ ssh_keys.stdout }}"
      tags:
        - ssh

    - name: deploy keys on all servers
      authorized_key: user=root key="{{ item[0] }}"
      delegate_to: "{{ item[1] }}"
      with_nested:
        - "{{ ssh_keys.stdout }}"
        - "{{groups['app']}}"
      tags:
        - ssh
